// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileAppend(arg1:string,arg2:string):Promise<string>;

export function FileRead(arg1:string):Promise<string>;

export function FileWrite(arg1:string,arg2:string):Promise<string>;

export function GetCurrentPath():Promise<string>;

export function GetInfo(arg1:string,arg2:string):Promise<string>;

export function GetListDir(arg1:string):Promise<string>;

export function GetUid(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function GzCH(arg1:string,arg2:string):Promise<string>;

export function SendTwi(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function UploadPic(arg1:string,arg2:string):Promise<string>;
