// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileAppend(arg1, arg2) {
  return window['go']['main']['App']['FileAppend'](arg1, arg2);
}

export function FileRead(arg1) {
  return window['go']['main']['App']['FileRead'](arg1);
}

export function FileWrite(arg1, arg2) {
  return window['go']['main']['App']['FileWrite'](arg1, arg2);
}

export function GetCurrentPath() {
  return window['go']['main']['App']['GetCurrentPath']();
}

export function GetInfo(arg1, arg2) {
  return window['go']['main']['App']['GetInfo'](arg1, arg2);
}

export function GetListDir(arg1) {
  return window['go']['main']['App']['GetListDir'](arg1);
}

export function GetUid(arg1) {
  return window['go']['main']['App']['GetUid'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GzCH(arg1, arg2) {
  return window['go']['main']['App']['GzCH'](arg1, arg2);
}

export function SendTwi(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendTwi'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadPic(arg1, arg2) {
  return window['go']['main']['App']['UploadPic'](arg1, arg2);
}
